
<!DOCTYPE html>
<html lang="fr">
    <head>
        <?php include('views/inc/_head.phtml'); ?>
    </head>
    <body>
        <div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
            <div class="container text-center">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <i class="bi bi-exclamation-triangle display-1 text-primary"></i>
                        <h1 class="mb-4"><?= $errorMessage ?></h1>
                        <p class="mb-4"></p>
                        <a class="btn btn-primary py-3 px-5" href="<?= URL ?>">Retour à l'accueil</a>
                    </div>
                </div>
            </div>
        </div>
        <?php include('views/inc/_footer.phtml'); ?>
    </body>
</html>
