<!DOCTYPE html>
<html lang="fr">
    <head>
        <?php include('views/inc/_head.phtml'); ?>
    </head>
    <body>
        <div class="container mt-3">
            <h3>Connexion</h3>
            <p>Veuillez remplir le formulaire pour vous connecter.</p>
                
            <form action="" method="post" id="login-form">
                <div class="mb-3 mt-3">
                    <label for="email" class="form-label">Email:</label>
                    <input type="email" class="form-control" id="email" placeholder="Entrez votre adresse email" name="email" value="sergetouvoli@outlook.fr">
                    <span class="error-message text-danger fw-bold" data-error="email"></span>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Mot de passe:</label>
                    <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="password" value="*******************">
                    <span class="error-message text-danger fw-bold" data-error="password"></span>
                </div>
                <p>Vous n'avez pas de compte ? <a href="<?= URL.REGISTER_PAGE ?>">Inscrivez-vous</a></p>
                <button type="submit" class="btn btn-primary">Soumettre</button>
            </form>
        </div>

        <script src="<?= URL ?>public/js/functions.js"></script>
        <script src="<?= URL ?>public/js/login.js"></script>
        <?php include('views/inc/_footer.phtml'); ?>
    </body>
</html>